---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-svc
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
  externalIPs:
    - 192.168.7.211
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ingress
  namespace: guestbook
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"    
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: test.s2grupo.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook-ui-svc
            port:
              name: http
  tls:
  - hosts:
    - test.s2grupo.es
    secretName: cert-test
  ingressClassName: nginx
