apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-lb-svc
  namespace: prometheus
  annotations:
    metallb.universe.tf/address-pool: static_pool
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    name: http
  selector:
    app: prometheus
    component: server
  loadBalancerIP: 192.168.100.15