apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-lb-svc
  namespace: prometheus
  annotations:
    metallb.universe.tf/address-pool: static_pool
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    name: http
  selector:
    app: prometheus
    component: server
    release: prometheus
  loadBalancerIP: 192.168.100.11
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: prometheus-ingress
  namespace: prometheus
spec:
  rules:
    - host: prometheus.home.lab
      http:
        paths:
          - backend:
              service: 
                name: prometheus-grafana
                port:
                  number: 80
            path: /
            pathType: Prefix
