apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-nfs-pv01
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.21
    path: "/mnt/discoNFS/shared/pv05"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-nfs-pvc
spec:
  storageClassName: storage-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi